POST http://localhost:5000/api/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2N2U4MjkwZDdkMWRhYjQzY2E0MzUxZjMiLCJpYXQiOjE3NDMyNzY4NDcsImV4cCI6MTc0MzM2MzI0N30.iuG1nIIYJh6MLHuso0Mkmq6X9f7VdYMXvTlpM_LYyxI

{
	"title": "Mechanical Gaming Keyboard",
		"price": 89.99,
		"description": "RGB backlit keyboard with tactile switches for a high-performance gaming experience.",
    "category": "Electronics",
    "image": "https://example.com/smart.jpg"
}