GET http://localhost:5000/

###
POST http://localhost:5000/api/users
Content-Type: application/json

{
	"username": "sarah_miller",
	"email": "sarah.miller@example.com",
	"password": "S@rahPass99",
	"isAdmin": true
}

###
GET http://localhost:5000/api/users/profile

###
GET http://localhost:5000/api/users

###
GET  http://localhost:5000/api/users/67e6f7005efe4fa5d4b43ea8

###
POST http://localhost:5000/api/users/login
Content-Type: application/json

{
    "email": "sarah.miller@example.com",
	"password": "S@rahPass99"
}
###

POST http://localhost:5000/api/users/login
Content-Type: application/json

{
    "email": "alice@beta.com",
    "password": "alphabetagamma"
}

###
POST  http://localhost:5000/api/users/logout

###
PUT http://localhost:5000/api/users/profile
Content-Type: application/json

{
    "newUsername": "alice42",
    "newEmail": "alice@alpha.com"
}

###
DELETE http://localhost:5000/api/users/67e6f6385efe4fa5d4b43e99

###
DELETE http://localhost:5000/api/users/

###
POST http://localhost:5000/api/products
Content-Type: application/json

{
	"title": "Stainless Steel Water Bottle",
	"price": 18.5,
	"description": "Insulated, leak-proof bottle that keeps drinks cold for 24 hours and hot for 12 hours.",
    "category": "Electronics",
    "image": "/image"
}

###
GET http://localhost:5000/api/products


