POST http://localhost:5000/api/users/signup
Content-Type: application/json

{
		"username": "sarah_miller",
		"email": "sarah.miller@example.com",
		"password": "S@rahPass99",
        "confirmpassword": "S@rahPass99"
}

###
POST http://localhost:5000/api/users/
Content-Type: application/json

{
		"username": "olivia_taylor",
		"email": "olivia.taylor@example.com",
		"password": "Taylor@Secure",
		"isAdmin": true
	}

###
GET http://localhost:5000/api/users/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2N2U4MjkwZDdkMWRhYjQzY2E0MzUxZjMiLCJpYXQiOjE3NDM1ODI4NzQsImV4cCI6MTc0MzY2OTI3NH0.jwf3QK3OlNXEFqNIhwtZAQvJcbw-J54sHje71nRRMbI