GET http://localhost:3000/ping

###
POST http://localhost:3000/api/auth/signup
Content-Type: application/json

{
    "username": "sarah_miller",
    "email": "sarah.miller@example.com",
    "password": "S@rahPass99",
    "confirmPassword": "S@rahPass99"
}

###
POST http://localhost:3000/api/auth/signup
Content-Type: application/json

{
    "username": "shreyash",
    "email": "shreyash@alpha.com",
    "password": "secret_secure",
    "confirmPassword": "secret_secure"
}
